#!/bin/bash
#
# Script      : checkproc
# Author(s)   : Pol Warnimont
# Create date : 2015-04-27
# Version     : 0.9
#
# Description : A check script for SRVMON - Check process count
#
# Changelog
# ---------
#  2015-04-27 : Created script.
#  2015-04-30 : Changed license to AGPLv3.
#
# License
# -------
#  Copyright (C) 2015  Pol Warnimont
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>. 

PROCCOUNT=`ps aux | wc -l`

if [ $PROCCOUNT -gt 200 ]
then
  EXCODE=2
  OUTPUT="$PROCCOUNT running processes (>200)!"
elif [ $PROCCOUNT -gt 150 ]
then
  EXCODE=1
  OUTPUT="$PROCCOUNT running processes (>150)!"
else
  EXCODE=0
  OUTPUT="Process count Ok ($PROCCOUNT)."
fi

echo "$EXCODE;$OUTPUT"
