#!/bin/sh
### BEGIN INIT INFO
# Provides:          srvmon-updater
# Required-Start:    $local_fs $syslog $network $named
# Required-Stop:     $local_fs $syslog $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SRVMON-UPDATER initscript
# Description:       This initscript is used to start the SRVMON
#                    DIRECTOR UPDATER program. The UPDATER is used
#                    to determine the online status of the hosts
#                    which are defined in the database. Please
#                    contact the package maintainer for any questions
#                    regarding the SRVMON DIRECTOR UPDATER.
### END INIT INFO

# Author: Pol Warnimont <pwarnimo@gmail.com>

SERVICE_NAME=srvmon-updater
PATH_TO_SRVMON=/usr/sbin/srvmon-updater
PID_PATH_NAME=/var/run/$SERVICE_NAME.pid
case $1 in
	start)
		echo "Starting $SERVICE_NAME"
		if [ ! -f $PID_PATH_NAME ]
		then
			nohup $PATH_TO_SRVMON /tmp 2>> /dev/null >> /dev/null & echo $! > $PID_PATH_NAME
			echo "$SERVICE_NAME has started."
		else
			echo "$SERVICE_NAME is already running!"
		fi
	;;

	stop)
		if [ -f $PID_PATH_NAME ]
		then
			PID=$(cat $PID_PATH_NAME)
			echo "$SERVICE_NAME stopping..."
			kill $PID
			echo "$SERVICE_NAME is now stopped."
			rm $PID_PATH_NAME
		else
			echo "$SERVICE_NAME is already stopped!"
		fi
	;;

	status)
		if [ -f $PID_PATH_NAME ]
		then
			PID=$(cat $PID_PATH_NAME)
			kill -0 $PID
			if [ $? -eq 0 ]
			then
				echo "$SERVICE_NAME is running."
			else
				echo "$SERVICE_NAME is stopped, but the PID still exists."
				echo "Please delete $PID_PATH_NAME"
			fi
		else
			echo "$SERVICE_NAME is stopped."
		fi
	;;
esac
