#!/bin/bash
#
# Script      : chkssh
# Author(s)   : Pol Warnimont
# Create date : 2015-04-27
# Version     : 1.0 R1
#
# Description : A SRVMON check script - Check if SSH daemon is running
#
# Changelog
# ---------
#  2015-04-27 : Create script
#  2015-04-30 : Changed license to AGPLv3.
#
# License
# -------
#  Copyright (C) 2015  Pol Warnimont
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

/etc/init.d/ssh status > /dev/null 2>&1

if [ $? -eq 0 ]
then
  EXCODE=0
  MSG="SSH is running!"
else
  EXCODE=1
  MSG="SSH is stopped!"
fi

echo "$EXCODE;$MSG"
