######################################################################
# Automatically generated by qmake (3.0) Mi. Feb. 3 15:58:19 2016
######################################################################

TEMPLATE = app
TARGET = build/srvmon-agent
INCLUDEPATH += . src

# Input
HEADERS += src/task.h
SOURCES += src/main.cpp src/task.cpp
