######################################################################
# Automatically generated by qmake (3.0) Mo. Feb. 15 13:48:38 2016
######################################################################

TEMPLATE = app
TARGET = build/agent
INCLUDEPATH += . src

# Input
HEADERS += src/httprequestworker.h src/service.h src/services.h src/task.h
SOURCES += src/httprequestworker.cpp \
           src/main.cpp \
           src/service.cpp \
           src/services.cpp \
           src/task.cpp

QT += network

CONFIG += c++11
