######################################################################
# Automatically generated by qmake (3.0) Do. Feb. 4 10:53:34 2016
######################################################################

TEMPLATE = app
TARGET = build/srvmon-agent
INCLUDEPATH += . src

# Input
HEADERS += src/httprequestworker.h src/task.h
SOURCES += src/httprequestworker.cpp src/main.cpp src/task.cpp

QT += network
