#!/bin/bash
#
# Script      : chketh
# Author(s)   : Pol Warnimont
# Create date : 2015-05-27
# Version     : 1.0 R1
#
# Description : A check script for SRVMON - Network interface status.
#
# Changelog
# ---------
#  2015-05-26 : Created script.
#  2016-02-03 : Changed license.
#
# License
# -------
#  Copyright (C) 2016  Pol Warnimont
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [ $# -eq 1 ]
then
	if [ "`ifconfig | grep -o $1`" = "$1" ]
	then
		OUTPUT="Interface $1 is up!"
		EXCODE=0
	else
		OUTPUT="Interface $1 is down!"
		EXCODE=2
	fi

	echo "$EXCODE;$OUTPUT"
	exit $EXCODE
else
	echo "Syntax error!"
	echo "Usage: $0 <if name>"
	echo "Ex.:   $0 eth0"
	echo ""
	echo "Copyright (C) 2016  Pol Warnimont"
	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
fi
