#!/bin/bash
#
# Script      : chkmem
# Author(s)   : Pol Warnimont
# Create date : 2015-05-27
# Version     : 1.0 R1
#
# Description : A check script for SRVMON - Free memory status.
#
# Changelog
# ---------
#  2015-05-26 : Created script.
#  2016-02-03 : Changed license.
#  2016-02-26 : Disabled newline on output.
#
# License
# -------
#  Copyright (C) 2016  Pol Warnimont
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [ $# -eq 2 ]
then
	TOTALMEM=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`
	MEMAVAIL=`cat /proc/meminfo | grep MemAvailable | awk '{print $2}'`

	PERCFREE=$(echo "scale=2; ($MEMAVAIL/$TOTALMEM)*100" | bc)

	if [ `echo $PERCFREE"<"$2 | bc -l` -eq 1 ]
	then
		OUTPUT="Free memory below critical threshold ($PERCFREE% < $2%)!"
		EXCODE=2
	elif [ `echo $PERCFREE"<"$1 | bc -l` -eq 1 ]
	then
		OUTPUT="Free memory below warning threshold ($PERCFREE% < $1%)!"
		EXCODE=1
	else
		OUTPUT="Memory Ok ($PERCFREE% free)."
		EXCODE=0
	fi

	echo -n "$EXCODE;$OUTPUT"
	exit $EXCODE
else
	echo "Syntax error!"
	echo "Usage: $0 <warning % threshold> <critical % threshold>"
	echo "Ex.:   $0 20 5"
	echo ""
	echo "Copyright (C) 2016  Pol Warnimont"
	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
fi
