#!/bin/bash
#
# Script      : chkping
# Author(s)   : Pol Warnimont
# Create date : 2015-04-27
# Version     : 1.1 R1
#
# Description : A SRVMON check script - Check if gateway is reachable
#
# Changelog
# ---------
#  2015-04-27 : Created script.
#  2015-04-30 : Changed license to AGPLv3.
#  2015-05-26 : Modifying script.
#  2016-02-03 : Changed license.
#  2016-02-26 : Disabled newline on output.
#
# License
# -------
#  Copyright (C) 2016  Pol Warnimont
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

FAILCNT=0
PINGCNT=0

if [ $# -eq 3 ]
then
	while [ $PINGCNT -ne $2 ]
	do
		ping -c1 $1 > /dev/null 2>&1
		
		if [ $? -ne 0 ]
		then
			((FAILCNT = FAILCNT + 1))
		fi

		((PINGCNT = PINGCNT + 1))
	done

	if [ $FAILCNT -eq $2 ]
	then
		EXCODE=2
		OUTPUT="$1 is unreachable!"
	elif [ $FAILCNT -ge $3 ]
	then
		EXCODE=1
		OUTPUT="$FAILCNT of $2 pings failed!"
	else
		EXCODE=0
		OUTPUT="$1 is reachable!"
	fi

	echo -n "$EXCODE;$OUTPUT"
	exit $EXCODE
else
	echo "Syntax error!"
	echo "Usage: $0 <ip addr> <ping count> <warn count>"
	echo "Ex.:   $0 192.168.1.1 4 2"
	echo ""
	echo "Copyright (C) 2016  Pol Warnimont"
	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
	exit 1
fi
