#!/bin/bash
#
# Script      : chkspace
# Author(s)   : Pol Warnimont
# Create date : 2015-05-26
# Version     : 1.0 R1
#
# Description : A check script for SRVMON - Drive space status.
#
# Changelog
# ---------
#  2015-05-26 : Created script.
#  2016-02-03 : Changed license.
#  2016-02-26 : Disabled newline on output.
#
# License
# -------
#  Copyright (C) 2016  Pol Warnimont
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

if [ $# -eq 3 ]
then
	FREESPACE=`df -h $1 | tail -n +2 | tr -s " " |cut -d" " -f4 | sed 's/G$//'`

	if [ $(echo "$FREESPACE < $3" | bc) -eq 1 ]
	then
		OUTPUT="Drive space below critical level (<${3}G)."
		EXCODE=2
	elif [ $(echo "$FREESPACE < $2" | bc) -eq 1 ]
	then
		OUTPUT="Drive space below warning level (<${2}G)."
		EXCODE=1
	else
		OUTPUT="Drive space ok (${FREESPACE}G free)."
		EXCODE=0
	fi

	echo -n "$EXCODE;$OUTPUT"
	exit $EXCODE
else
	echo "Syntax error!"
	echo "Usage: $0 <mount point> <warning level> <critical level>"
	echo "Ex.:   $0 / 4 1"
	echo ""
	echo "Copyright (C) 2016  Pol Warnimont"
	echo "This script ($0) comes with ABSOLUTELY NO WARRANTY!"
fi
