######################################################################
# Automatically generated by qmake (3.0) Mo. Feb. 1 10:20:11 2016
######################################################################

TEMPLATE = app
TARGET = 3.0
INCLUDEPATH += .

# Input
HEADERS += task.h
SOURCES += main.cpp task.cpp

QT += sql
QTPLUGIN += qsqlmysql
